### PR TITLE
AMSR and MWSFY3 files with reordered varno entries

### PR DESCRIPTION
**Pull request by ctgh**
## Description

Please merge at the same time as JCSDA-internal/ioda#652

### CODE REVIEW

**Comment by ctgh** [comment]
@fabien-mo Can you please check that the ordering of entries in these files is correct?

**Review by DJDavies2 — APPROVED** [review]

**Comment by ctgh** [comment]
@fabien-mo Based on what we discussed this morning I think the output is now in the correct order. Please let me know if it isn't.

**Review by fabien-mo — APPROVED** [review]
AMSR-2 test file is now OK. MWSFY3 looks ok too: 13 MWTS channels first - missing in this case - followed by 15 MWHS channel s. I assumed it's because the platform is FY-3C. But haven't made any test for MWSFY3.

**Comment by ctgh** [comment]
Thanks for checking!

**Pull request merged**
