### PR TITLE
Updated reference file.

### PR DESCRIPTION
**Pull request by DJDavies2**
See https://github.com/JCSDA-internal/ioda/pull/436, this is an updated GPSRO reference file.

### CODE REVIEW

**Review by srherbener — APPROVED** [review]

**Comment by neill-b** [comment]
The file looks mostly good.  It seems to be missing impact parameter (should be an array of length nlocs).

**Comment by srherbener** [comment]
Since jcsda-internal/ioda/pull/436 got superseded by jcsda-internal/ioda/pull/450, does this PR get superseded by #41? Thanks!

**Comment by DJDavies2** [comment]
Yes, sorry.

**Comment by srherbener** [comment]
No worries, and thanks for taking care of this

**Pull request closed without merging**
