### PR TITLE
Update bool fill value in reference netcdf file

### PR DESCRIPTION
**Pull request by fmahebert**
## Description

Update a IODA reference file for the missingValue changes in https://github.com/JCSDA-internal/oops/pull/2234

## Dependencies

List the other PRs that this PR is dependent on:
- https://github.com/JCSDA-internal/oops/pull/2234

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by srherbener** [comment]
@fmahebert I just tried testing this with the corresponding oops branch, and I still see the `test_ioda_obsspace_default_fill_values_cmp` test failure:
```
DIFFER : VARIABLE : DummyBoolVar : ATTRIBUTE : _FillValue : VALUES : 0x00 <> 0x05
```

It appears that the develop version and the feature/templated_missingValue version of the `default_fill_values_out.nc4` are the same.

Or perhaps I'm doing something wrong when testing this.

**Comment by fmahebert** [comment]
Nope, you're correct — I just (hopefully correctly this time?) fixed it. I'll make a test dummy PR in the IODA repo to confirm...

**Comment by srherbener** [comment]
No worries, thanks for fixing this! and for adding the dummy test PR.

**Review by srherbener — APPROVED** [review]
Thanks for all your work to fix warnings! It's much appreciated.

**Review by ytremolet — APPROVED** [review]

**Pull request merged**
