### PR TITLE
Allow the upgrader and the ioda reader to handle an input file with zero observations

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR contains test files for jcsda-internal/ioda/pull/604 which enables the ioda reader and upgrader to handle input files with zero observations.

### Issue(s) addressed

- fixes jcsda-internal/ioda/issues/445

## Acceptance Criteria (Definition of Done)

All ioda tests pass, which includes a couple tests with zero obs input files.

## Dependencies

- [ ] merge with jcsda-internal/ioda/pull/604

## Impact

None

### CODE REVIEW

**Comment by srherbener** [comment]
@rhoneyager, @sking112 if you have time please review soon. It's a quick review - just adding new test files for the new zero obs tests. Thanks!

**Comment by sking112** [comment]
> @rhoneyager, @sking112 if you have time please review soon. It's a quick review - just adding new test files for the new zero obs tests. Thanks!

Is there a ctest for these files?

**Comment by srherbener** [comment]
Yes, these are new files for the new ctests introduced in jcsda-internal/ioda/pull/604.

**Review by sking112 — APPROVED** [review]

**Comment by srherbener** [comment]
Thanks @sking112 for your quick response!

**Pull request merged**
