### PR TITLE
Removed unused varnos.

### PR DESCRIPTION
**Pull request by DJDavies2**
This changes shrinks some of the ODB input files (the satellite radiance ones) by throwing out rows relating to varnos we are not extracting.  There is no affect on outputs.

Not sure how to trigger the AWS tests for this?

### CODE REVIEW

**Comment by wsmigaj** [comment]
> Not sure how to trigger the AWS tests for this?

You could create a `feature/SmallerODBs` branch in `ioda`, push an empty commit to it and open a pull request in `ioda`.

**Comment by DJDavies2** [comment]
I've done that.

**Review by srherbener — APPROVED** [review]
Thanks!

**Comment by srherbener** [comment]
I'm going to go ahead and merge this in since all the tests passed in the feature/SmallerODBs PR in ioda. I will then close the ioda PR since its only purpose was to run the tests on these files.

**Pull request merged**
