### PR TITLE
MWRI test file without  sensor azimuth angle

### PR DESCRIPTION
**Pull request by fabien-mo**
## Description

Data associated with https://github.com/JCSDA-internal/ioda/pull/761 for MWRI removal of azimuth angle.

### Issue(s) addressed

None

## Acceptance Criteria (Definition of Done)

Reviewed 

## Dependencies

ioda https://github.com/JCSDA-internal/ioda/pull/761

## Impact

None

### CODE REVIEW

**Review by brettcandy — COMMENTED** [review]
is there a way to view whats in an hdf file?

**Comment by fabien-mo** [comment]
> is there a way to view whats in an hdf file?

It's in the format of JEDI nc files, you can use:
>> module load jedi/ufo-bundle-dev-stack
>> ncdump -h test-MWRI.hdf

**Comment by mikecooke77** [comment]
> is there a way to view whats in an hdf file?

Or my favourite: /home/h04/cfsa/SPS/bin/hdfview

**Review by brettcandy — APPROVED** [review]
thanks- i have now been able to verify that the file no longer contains the azimuth angle

**Pull request merged**
