### PR TITLE
Reconvert develop files - 2021-03-12

### PR DESCRIPTION
**Pull request by rhoneyager**
This PR regenerates the ioda-data files to fix issues with a missing final variable.

Closes https://github.com/JCSDA-internal/ioda/issues/143.

### CODE REVIEW

**Review by srherbener — APPROVED** [review]
I tested this with my feature/ioda-v2 branch and all tests except obsspace_mpi pass. obsspace_mpi has a known crash issue. Thank you for fixing this!

The files look good, however it seems that more of them won't work with ncdump. I think we can address that in a subsequent PR.

I had to adjust a couple "expected nvars" values and have a companion PR in ioda (jcsda-internal/ioda/pull/151).

**Comment by srherbener** [comment]
Noticed you just pushed a couple new files. I did a pull and re-ran tests, and all tests pass again (except for the crash in obsspace_mpi).

**Comment by rhoneyager** [comment]
Thanks @srherbener. The "expected nvars" were driving me crazy! How are these counted? iodatest_obsio_constructor.yml, for example, listed 64 variables and 5 dimensions, but the actual original file had 65 variables and 5 dimensions.

**Comment by srherbener** [comment]
The obsio and obsframe tests sets nvars to the number of regular variables in the file (ie, excluding dimension variables).

The ObsSpace however sets nvars to the number of variables in the ObsValue group. This is more consistent with what we call a variable in JEDI (as opposed to meta data).

**Comment by rhoneyager** [comment]
I wonder if ncdump is thrashing on the _Netcdf4Coordinates attribute that appears in some of the strings... The coords are no longer valid following string conversion.

**Comment by srherbener** [comment]
In the sondes file example, the original file has 65 regular variables and 5 dimension variables. When the first file showed up, variable_names@VarMetaData (dimensioned by nvars), was missing and I thought you were just cleaning up things that didn't fit into the nlocs, nchans scheme so I accepted the drop to 64 variables as okay. Now I realize that this was the bug so I'm glad that this is getting set back to the original 65.

**Comment by rhoneyager** [comment]
> I wonder if ncdump is thrashing on the _Netcdf4Coordinates attribute that appears in some of the strings... The coords are no longer valid following string conversion.

I just checked and this attribute **is** why these files are failing in ncdump. I will patch the code and regenerate ioda-data.

**Comment by srherbener** [comment]
> I wonder if ncdump is thrashing on the _Netcdf4Coordinates attribute that appears in some of the strings... The coords are no longer valid following string conversion.

I  think you might be correct. I tried a couple files and the ones without the _Netcdf4Coordinates attribute still work with ncdump. Any ideas why _Netcdf4Coordinates is in some files and not others?

**Comment by rhoneyager** [comment]
It's a rather vestigial attribute. Netcdf works fine without it, and it is applied inconsistently. I've added into the ioda-upgrade attribute drop list.

**Comment by srherbener** [comment]
I noticed another attribute: _Netcdf4Dimid

This one however doesn't correspond with ncdump failing. Thought I would mention it since it perhaps is another attribute that can be dropped.

I just submitted a ZenHub issue on this so that we can track this in ZenHub instead of in this PR.

**Pull request merged**
