### PR TITLE
Rename water_fraction to waterFraction in ref ctest file for AIRS

### PR DESCRIPTION
**Pull request by brettcandy**
## Description

As part of the variable renaming  in ufo (PR https://github.com/JCSDA-internal/ufo/pull/2588) the setsurface filter now expects the AIRS water fraction to be named _MetaData/waterAreaFraction_ rather than _MetaData/water_fraction_

This PR updates the ctest reference file for test test_ioda-convert_airs_odc

## Acceptance Criteria (Definition of Done)

updated hdf file produced by ctest contains waterFraction

## Dependencies

This PR should be merged at the same time as PR https://github.com/JCSDA-internal/ioda/pull/897 for ioda

# Impact

None

### CODE REVIEW

**Comment by srherbener** [comment]
@brettcandy please assign some reviewers. Thanks!

**Comment by brettcandy** [comment]
update to test reference following suggested rename to waterAreaFraction by reviewers https://github.com/JCSDA-internal/ioda-data/pull/129/commits/eda6faa726043cb500975be8a2668bb51babfd89

**Review by mikecooke77 — APPROVED** [review]
All ioda ctests in associated PR passing.

**Comment by BenjaminRuston** [comment]
@brettcandy I updated the text in the issue, assume nothing needs to be changed in test input data

**Review by BenjaminRuston — APPROVED** [review]
data for corresponding ctest update of water_fraction should not need name changing

**Pull request merged**
