### PR TITLE
Feature/odb satwind scatwind

### PR DESCRIPTION
**Pull request by james-cotton**
## Description

Updated test reference ODB output files for https://github.com/JCSDA-internal/ioda/pull/456

## Dependencies

Waiting on the following PRs:
- [ ] merge with JCSDA-internal/ioda/pull/456

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] ioda

### CODE REVIEW

**Review by DJDavies2 — APPROVED** [review]

**Comment by DJDavies2** [comment]
There is the GPSRO change that needs to be merged I think?

**Review by DJDavies2 — APPROVED** [review]
Okay once the GPSRO changed is merged.

**Comment by james-cotton** [comment]
After a bit of a hiccup (which I reverted) I think I have successfully merged the GPSRO change

**Review by srherbener — APPROVED** [review]

**Comment by srherbener** [comment]
I think the conflict exists in the sonde reference file due to a PR that recently got merged into develop (jcsda-internal/ioda/pull/433) which caused an update in the sonde reference file, while changes in this PR are causing other changes to the sonde reference file. If so, then you should be able to resolve this by making sure develop is merged into your companion ioda PR, running the odb sonde test and checking that the resulting sonde HDF5 file contains both the expected updates (from develop and changes in the ioda companion PR).

**Pull request merged**
