### PR TITLE
BUFR Backend Test Data

### PR DESCRIPTION
**Pull request by rmclaren**
## Description

Add test data required for the BUFR backend of IODA.

## Issues

https://github.com/JCSDA-internal/ioda/issues/1082

### CODE REVIEW

**Review by CoryMartin-NOAA — COMMENTED** [review]
This is a lot of new test data, do we need all of these or would a subset be sufficient?

**Comment by srherbener** [comment]
> This is a lot of new test data, do we need all of these or would a subset be sufficient?

Same question, as I suspect there is a lot of redundancy from the perspective of unit testing and code coverage.

**Comment by rmclaren** [comment]
There probably is some amount of redundancy, but it would be a project in its own right to come up with the minimal set of BUFR files we need. There are a lot of nuances in BUFR files. For example: repeated elements at the very ends of sequences can get very tricky to parse. Nested sequences of all types, especially binary ones can lead to problems and so on (there are very many scenarios)... Finding an exhaustive list of all the possible scenarios would be difficult, and it would be hard to identify real world BUFR files that cover many of them. So instead we have a big library of real world BUFR files that are organized different ways (internally) to give us confidence that things are working right... Having a large representative data set also helps identify issues we would not have thought of ourselves (example WMO BUFR files can be inconsistent even within themselvs with identically named subset that are actually constructed differently, etc...)

**Comment by CoryMartin-NOAA** [comment]
@rmclaren what's the rough amount of additional data here? is it like 10MB or 1+GB additional data?

**Comment by srherbener** [comment]
I think a pragmatic solution might be to split the data and testing into two sets: one for unit testing here and another for verifying the complete (or near-complete) set of instruments which could be done outside the ioda/ioda-data repos.

I believe this is what the Met Office is doing with the ODB backend. They have about 50 files checked into ioda-data and a bunch more in their own repos/testing framework.

If this sounds agreeable, perhaps an effective split could be accomplished by taking a small number of files each from a set of instruments types you want covered in the unit testing (eg, 5 or 6 radiance files, 5 or 6 hyperspectral radiance, 5 or 6 (or a little more) conventional, 5 or 6 ocean, etc). I suspect this would give you good coverage and do so without requiring a thorough anlysis of what branches of code are being exercised by each file.

What do you think?

**Comment by CoryMartin-NOAA** [comment]
I like @srherbener 's suggestion. @rmclaren if you are fine with this, we can work to setup a more comprehensive test on NOAA HPC with a staged full day's worth of data, and just put the bare minimum in the JEDI repos.

**Comment by rmclaren** [comment]
@CoryMartin-NOAA The bufr files add 25 MB to the size of bufr-data. The files are not full sized...

**Comment by CoryMartin-NOAA** [comment]
That's not too bad then, what is the total size of this repo? If this adds <10% then it's probably fine. But would probably still prefer to trim it down somewhat if possible and we can run more in depth tests on our HPC.

**Comment by rmclaren** [comment]
I'll work to try to minimize the amount of data. Just noticed the netcdf files take up way more space than the BUFR files.... I'd prefer not to split these tests as I want it to be immediately evident if something breaks.

**Comment by rmclaren** [comment]
@srherbener I've got a really strange problem. I'm using the `obsdataout` parameter in the ioda yaml files in order to generate HDF5 files which I can compare in the ctests. The problem is that doing this results in absurdly large HDF5 files. So for example  `ioda-data/testinput_tier_1/test_reference/iodatest_bufr_wmo_radiosonde.nc` blows up to like 1 Gig. When generating the same file in ioda-converters yielded a file that was only 133 KB. If I go to `ioda-data/testinput_tier_1/test_reference` and do `ncdump iodatest_bufr_wmo_radiosonde.nc > test.txt` test.txt ends up being only 728KB...

Comparing the ncdump header informtation I get the following:

ioda-converters/test/testoutput/bufr_read_wmo_radiosonde.nc 

```
netcdf bufr_read_wmo_radiosonde {
dimensions:
	Level = 5880 ;
	Location = 6 ;
variables:
	int Level(Level) ;
		Level:suggested_chunk_dim = 5880LL ;
	int Location(Location) ;
		Location:suggested_chunk_dim = 6LL ;

// global attributes:
		string :_ioda_layout = "ObsGroup" ;
		:_ioda_layout_version = 0 ;

group: MetaData {
  variables:
  	int64 dateTime(Location) ;
  		dateTime:_FillValue = 9223372036854775807LL ;
  		string dateTime:long_name = "dateTime" ;
  		string dateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
  	float latitude(Location) ;
  		latitude:_FillValue = 3.402823e+38f ;
  		string latitude:long_name = "Latitude" ;
  		string latitude:units = "degrees_north" ;
  	float longitude(Location) ;
  		longitude:_FillValue = 3.402823e+38f ;
  		string longitude:long_name = "Longitude" ;
  		string longitude:units = "degrees_east" ;
  } // group MetaData

group: ObsValue {
  variables:
  	float airTemperature(Location, Level) ;
  		airTemperature:_FillValue = 3.402823e+38f ;
  		string airTemperature:long_name = "Air Temperature" ;
  		string airTemperature:units = "K" ;
  		string airTemperature:coordinates = "longitude latitude Level" ;
  	float dewPointTemperature(Location, Level) ;
  		dewPointTemperature:_FillValue = 3.402823e+38f ;
  		string dewPointTemperature:long_name = "Dewpoint Temperature" ;
  		string dewPointTemperature:units = "K" ;
  		string dewPointTemperature:coordinates = "longitude latitude Level" ;
  	int windDirection(Location, Level) ;
  		windDirection:_FillValue = 2147483647 ;
  		string windDirection:long_name = "Wind Direction" ;
  		string windDirection:units = "degree" ;
  		string windDirection:coordinates = "longitude latitude Level" ;
  	float windSpeed(Location, Level) ;
  		windSpeed:_FillValue = 3.402823e+38f ;
  		string windSpeed:long_name = "Wind Speed" ;
  		string windSpeed:units = "m s-1" ;
  		string windSpeed:coordinates = "longitude latitude Level" ;
  } // group ObsValue
}
``` 

ioda-data/testinput_tier_1/test_reference/iodatest_bufr_wmo_radiosonde.nc

```
netcdf iodatest_bufr_wmo_radiosonde {
dimensions:
	Level = 5880 ;
	Location = UNLIMITED ; // (6 currently)
variables:
	int Level(Level) ;
		Level:_FillValue = -2147483643 ;
	int Location(Location) ;
		Location:_FillValue = -2147483643 ;

// global attributes:
		string :_ioda_layout = "ObsGroup" ;
		:_ioda_layout_version = 0 ;

group: DerivedObsError {
  variables:
  	float dewPointTemperature(Location) ;
  		dewPointTemperature:_FillValue = -3.368795e+38f ;
  	float windDirection(Location) ;
  		windDirection:_FillValue = -3.368795e+38f ;
  	float airTemperature(Location) ;
  		airTemperature:_FillValue = -3.368795e+38f ;
  	float windSpeed(Location) ;
  		windSpeed:_FillValue = -3.368795e+38f ;
  } // group DerivedObsError

group: MetaData {
  variables:
  	int64 dateTime(Location) ;
  		dateTime:_FillValue = -9223372036854775801LL ;
  		string dateTime:long_name = "dateTime" ;
  		string dateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
  	float latitude(Location) ;
  		latitude:_FillValue = -3.368795e+38f ;
  		string latitude:long_name = "Latitude" ;
  		string latitude:units = "degrees_north" ;
  	float longitude(Location) ;
  		longitude:_FillValue = -3.368795e+38f ;
  		string longitude:long_name = "Longitude" ;
  		string longitude:units = "degrees_east" ;
  } // group MetaData

group: ObsValue {
  variables:
  	float dewPointTemperature(Location, Level) ;
  		dewPointTemperature:_FillValue = -3.368795e+38f ;
  		string dewPointTemperature:coordinates = "longitude latitude Level" ;
  		string dewPointTemperature:long_name = "Dewpoint Temperature" ;
  		string dewPointTemperature:units = "K" ;
  	int windDirection(Location, Level) ;
  		windDirection:_FillValue = -2147483643 ;
  		string windDirection:coordinates = "longitude latitude Level" ;
  		string windDirection:long_name = "Wind Direction" ;
  		string windDirection:units = "degree" ;
  	float airTemperature(Location, Level) ;
  		airTemperature:_FillValue = -3.368795e+38f ;
  		string airTemperature:coordinates = "longitude latitude Level" ;
  		string airTemperature:long_name = "Air Temperature" ;
  		string airTemperature:units = "K" ;
  	float windSpeed(Location, Level) ;
  		windSpeed:_FillValue = -3.368795e+38f ;
  		string windSpeed:coordinates = "longitude latitude Level" ;
  		string windSpeed:long_name = "Wind Speed" ;
  		string windSpeed:units = "m s-1" ;
  } // group ObsValue
}

```

**Comment by srherbener** [comment]
@rmclaren wow! HDF5 Parallel IO doesn't support compression yet, so the obsdataout file will be uncompressed, but it shouldn't be 4 orders of magnitude difference. 

Is this example on Orion by any chance? (I don't have access to Hera). I can also try reproducing this on Orion or my laptop.

**Comment by rmclaren** [comment]
That example is from running on my machine (MacOS with clang toolchain), should replicate anywhere, however. Representing all the data as ASCII text results in only 728 KB, so there must be something more going on than the lack of compression.

**Comment by rmclaren** [comment]
@srherbener You should be able to checkout and build the `feature/bufr_backend` branch of ioda (and ioda-data), `cd build/test` and run `time_IodaIO.x testinput/iodatest_bufr_wmo_radiosonde.yaml`. The resulting nc file should appear in the testoutput directory.

**Pull request closed without merging**
