### PR TITLE
Feature/num radiance channels

### PR DESCRIPTION
**Pull request by DJDavies2**
Updated files for https://github.com/JCSDA-internal/ioda/pull/468.  There are updated input and output files for IASI and CrIS, plus an updated output file for AIRS (the input file already had the channel numbers).

### CODE REVIEW

**Review by srherbener — CHANGES_REQUESTED** [review]
The new test reference files are not getting constructed properly. There should not be an nchans variable in the MetaData, ie MetaData/nchans should not exist.

It looks like you created the MetaData/nchans variable to hold the selected channel numbers. That is, the nchans (in the top level) variable has values 1-n (n is number of channels) and the MetaData/nchans variable has the selected channel numbers (16, 38, 49, ..., 7885, 8007) repeated nlocs times.

Instead only the top-level nlocs variable should exist with its values being set to the selected channels (16, 38, 49, ..., 7885, 8007).

**Comment by DJDavies2** [comment]
> The new test reference files are not getting constructed properly. There should not be an nchans variable in the MetaData, ie MetaData/nchans should not exist.
> 
> It looks like you created the MetaData/nchans variable to hold the selected channel numbers. That is, the nchans (in the top level) variable has values 1-n (n is number of channels) and the MetaData/nchans variable has the selected channel numbers (16, 38, 49, ..., 7885, 8007) repeated nlocs times.
> 
> Instead only the top-level nlocs variable should exist with its values being set to the selected channels (16, 38, 49, ..., 7885, 8007).

I've updated reference files for this.

**Comment by wsmigaj** [comment]
The `nchans` variable in `test-AIRS.hdf` ends with about ten `-2147483648` entries. Is this expected?

**Comment by DJDavies2** [comment]
> The `nchans` variable in `test-AIRS.hdf` ends with about ten `-2147483648` entries. Is this expected?

The size of the nchans array is the maximum of the number of brightness temperatures and the number of radiances.  There are only as many channel numbers as there are brightness temperatures.

**Comment by srherbener** [comment]
@DJDavies2 thank you for restructuring the files. I think their structures look good now. However, the ODB missing values (-2147483648 entries) won't work. The nlocs and nchans variables are different than the rest of the variables since they are associated with dimensions (the HDF term for this kind of variable is "dimension scale"). Dimension scales hold the coordinate values for that dimension.

For nchans, the coordinate values are the channel numbers which are used for finding channels that are selected by UFO obs operators. In the AIRS file, the first three nchans values are 1, 6, 7; so if the operator selects channel 6, then that gets translated to pulling out the 2nd index along the channel dimension in the variable -> brightness_temperature[*, 1].

Having a channel number be the missing value could be problematic with the selection, but it also might be indicating something might be wrong with the formation of the 2D (nlocs X nchans) variables as in the following example.

I wonder if the effort to truncate the ODB file (for unit testing purposes) is contributing to this result. Say you have 11 channels and you pull out the first 100 locations. My understanding of the layout in the ODB file is that a radiance variable simply gets unfolded into the obsvalue column (much in the same manner that a 2D array is stored in memory). If that is correct, then taking the first 100 observations when there are 11 channels will end up leaving you 10 observations short of pulling out enough observations to fold the data back into a complete 2D array. That is, the first location consists of the first 11 observations (1-11), the second location with the second set of 11 observations (12-22), ..., 9th location (88-99), then the 100th obs goes into the beginning of the 10th location, leaving 10 missing spots. Sorry if this isn't what's going on, just thought I would mention it in case it's helpful.

**Comment by DJDavies2** [comment]
This isn't the truncation, this is due to the difference between the number of radiances and the number of brightness temperatures.  The nchans value is set to whatever is larger, the number of radiances or number of brightness temperatures.  Whatever set of values is smaller gets padded with missing data values.  This could be the list of channel numbers, meaning that this needs to be padded as well.

**Comment by mikecooke77** [comment]
> This isn't the truncation, this is due to the difference between the number of radiances and the number of brightness temperatures. The nchans value is set to whatever is larger, the number of radiances or number of brightness temperatures. Whatever set of values is smaller gets padded with missing data values. This could be the list of channel numbers, meaning that this needs to be padded as well.

I was wondering whether we should just provide either the BT's or the radiances depending on which data are in the MetDB.  For IASI for example we store radiances and then calculate the BT's in OPS (currently the files produced for JEDI contain a BT array full of missing data).  

In JEDI we would create brightness_temperature@DerivedObsValue during the ufo processing and therefore there is no need for the current brightness_temperature@ObsValue (full of missing data) to be created.  Is there a case where we use valid radiances and valid BT's?  If we only have one type of ObsValue then the above issue goes away.

**Comment by DJDavies2** [comment]
CrIS brightness temperatures have 22 actual numbers, the rest missing.  IASI has 19 actual numbers, the rest missing.  Are these brightness temperatures actually used by OPS?

**Comment by mikecooke77** [comment]
Looking at the [elements list (Met Office only)](https://code.metoffice.gov.uk/trac/da/browser/Elements/trunk/ATMOS/gl/CrIS_CRIMSS.elements) in OPS.  CrIS has 399 radiances and there are 22 BT's from ATMS.  I think therefore the data in JEDI should have nchans of size 399.  There should be another coordinate (maybe ancillary_nchans) which has 22 elements in this case.

For IASI equivalent elements have 20 ATOVs (AMSU-A 1-15, AMSU-B 1-5) BTs attached and 314 scaled radiances.  In this case the nchans would be of size 314 and the ancillary_nchans dimension would be 20.

**Comment by DJDavies2** [comment]
The problem is that the Jedi model as I understand it is that there can only be one coordinate in addition to nlocs, i.e. nchans.  I don't know how to resolve this.

**Comment by mikecooke77** [comment]
OK, in which case let me dig a bit deeper in OPS and just check whether or not they are used.

**Comment by srherbener** [comment]
@DJDavies2 and @mikecooke77 thanks for the explanation. One thing to note is that currently ioda wants 2D variables (nlocs X nchans) but the underlying data model (ioda-engines) can handle 3D, 4D, etc. variables (not limited to 2D). The work that I'm doing to replace the get_db/put_db interface in the ObsSpace will make that available. So, for now we are limited to 2D but in the next month or so we should be able to handle higher dimension variables.

On some instruments, there appears to be a one-to-one correspondence between radiance channels and brightness temperature channels (ie, you can have 2 variables, both with the same nchans). Are you saying that in this case that's not true. For example with CrIS you take 399 radiance channels and combine them to produce 22 brightness temperature channels.

If I've got it correct now, then today we will need to put radiance and brightness temperature into two different ObsSpace objects. The radiance ObsSpace will have nchans = 399, and the brightness temperature ObsSpace will have nchans = 22. However, as I mentioned above, in the near future we will be able to support one ObsSpace with a single 3D variable (nlocs X rad_nchans X bt_nchans) that could hold both radiance and brightness temperature.

**Comment by DJDavies2** [comment]
This isn't about 2d vs 3d variables.  It is about multiple 2d variables that have different 2nd dimensions (i.e. different values for nchans).  So for instance CrIS has 399 radiances and 22 brightness temperatures but because there can only be one value of nchans both radiances and brightness temperatures need to be stored in an array of 399 elements in the second dimension.

**Comment by srherbener** [comment]
> This isn't about 2d vs 3d variables. It is about multiple 2d variables that have different 2nd dimensions (i.e. different values for nchans). So for instance CrIS has 399 radiances and 22 brightness temperatures but because there can only be one value of nchans both radiances and brightness temperatures need to be stored in an array of 399 elements in the second dimension.

Thanks, you're right. What I said before about the 3D variable doesn't make sense.

We can't have missing values in the dimension variables. If we need to have both radiance and brightness temperature available in a DA run, then we need to create two distinct ObsSpace objects: one for radiance (nchans = 399) and one for brightness temperatures (nchans = 22). In other words, we need to end up with two ioda files: one with radiance, the other with brightness temperature.

**Comment by wsmigaj** [comment]
@srherbener Would it be possible (now or after the refactoring you mentioned) to have two 2d variables, one of size nlocs x nchans and another nlocs x nradiancechans (where nlocs, nchans and nradiancechans are three different dimension scales)?

**Comment by mikecooke77** [comment]
I think we can omit the microwave data when processing the hyperspectral IR.  After chatting with Ed Pavelin, it appears we have had thoughts about using them together but have never done this in the global processing.  Looking at the OPS it looks this is also the case with the UKV.

Therefore for CrIS just the 399 radiances are needed and for IASI the 314 scaled radiances.

**Comment by srherbener** [comment]
> @srherbener Would it be possible (now or after the refactoring you mentioned) to have two 2d variables, one of size nlocs x nchans and another nlocs x nradiancechans (where nlocs, nchans and nradiancechans are three different dimension scales)?

Unfortunately, I don't think that will work now, but could work after refactoring.

Another thing to consider with this is the ioda conventions (which includes specifications for dimensions) work that the OBS group is doing. This is a new use case that should be discussed.

**Comment by wsmigaj** [comment]
> Unfortunately, I don't think that will work now, but could work after refactoring.

Thank you!

**Comment by DJDavies2** [comment]
I've updated the files for CrIS and IAS (and CrISFSR and HIRAS although I don't think those are to be used).  More comment in the ioda issue.

**Review by wsmigaj — APPROVED** [review]

**Review by mikecooke77 — APPROVED** [review]
I've checked the nchans and ObsValue arrays for the 4 hdf files and they look good to me.

**Comment by srherbener** [comment]
@DJDavies2 looks good now. Thank you for your patience and diligence as we worked through this (and the ioda) PR.

**Review by srherbener — APPROVED** [review]

**Pull request merged**
