### PR TITLE
odb update

### PR DESCRIPTION
**Pull request by fabien-mo**
## Description

These are the test files to be used as reference for ioda ctest updated in https://github.com/JCSDA-internal/ioda/pull/478 

### Issue(s) addressed

https://github.com/JCSDA-internal/ioda/issues/385

## Acceptance Criteria (Definition of Done)

 The right data are extracted from the ODBs for your observation type.

## Dependencies

N/A

## Impact

ioda-data

### CODE REVIEW

**Review by brettcandy — COMMENTED** [review]
i have checked what is contained within _test-AMSR.hdf_ and _test-GMIHigh.hdf_  The AMSR file seems fine , whereas GMIHigh is still missing variable initial_vertco_reference is this expected?

**Comment by DJDavies2** [comment]
It is probably worth merging https://github.com/JCSDA-internal/ioda-data/pull/46 and retesting.

**Comment by fabien-mo** [comment]
> 
> 
> It is probably worth merging #46 and retesting.

Thank you David, that's done now.

**Comment by fabien-mo** [comment]
> 
> 
> i have checked what is contained within _test-AMSR.hdf_ and _test-GMIHigh.hdf_ The AMSR file seems fine , whereas GMIHigh is still missing variable initial_vertco_reference is this expected?

Right, the Push command did not pick that change up the first time, should be fine now.

**Review by DJDavies2 — APPROVED** [review]

**Pull request merged**
