### PR TITLE
New output files for ioda 1192

### PR DESCRIPTION
**Pull request by DJDavies2**
build-group=https://github.com/JCSDA-internal/ioda/pull/1192

## Description

Updated data files for https://github.com/JCSDA-internal/ioda/pull/1192.

## Issue(s) addressed

#182.

### CODE REVIEW

**Review by mikecooke77 — COMMENTED** [review]
Looking at the ioda change I don't understand why the aircraft and atms_time files are changed?

**Review by srherbener — APPROVED** [review]
From the perspective of keeping the files small and the ctests quick, these files look good. However, we need to get @mikecooke77's comment addressed before merging.

**Comment by DJDavies2** [comment]
> Looking at the ioda change I don't understand why the aircraft and atms_time files are changed?

There is a new column, processed_data, which means the ODB's are all different and need updating.  However there should be no difference apart from the new column.

**Comment by srherbener** [comment]
@mikecooke77, @matthewrmshin, @ctgh we need another review before we can merge this and jcsda-internal/ioda/pull/1192.

@mikecooke77 did your comment get addressed?

Thanks!

**Review by matthewrmshin — APPROVED** [review]
Tested in my environment. Works as expected.

**Comment by srherbener** [comment]
@matthewrmshin thanks for the quick response. I think @DJDavies2 has addressed @mikecooke77's comment (sorry if I'm wrong about this) so I am going to merge now. Thanks everyone!

**Pull request merged**
