### PR TITLE
Change sensorScanPosition from float to int

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

To resolve completely the inconsistent usage of float and integer types for `sensorScanPosition` the ioda-data files were changed to match the integer type.

## Issue(s) addressed

See the associated dependency for issue in UFO.  A separate one in this repo was not created.

https://github.com/JCSDA-internal/ufo/pull/2916

Depends on [ufo-data PR 343](https://github.com/JCSDA-internal/ufo-data/pull/343)
Coordinate with [ioda-data PR 161](https://github.com/JCSDA-internal/ioda-data/pull/161)
Coordinate with [ioda-converters PR 1287](https://github.com/JCSDA-internal/ioda-converters/pull/1287)
Coordinate with https://github.com/JCSDA-internal/ioda/pull/1046

Also DEPENDS on [r2d2-ingest issue 40](https://github.com/JCSDA-internal/r2d2-ingest/issues/40)

## Dependencies

[UFO PR 2916](https://github.com/JCSDA-internal/ufo/pull/2916)

## Impact

With coordinated PRs merged in `ioda-converters` and `ufo` and `ufo-data` no other impacts are expected.

### CODE REVIEW

**Review by srherbener — APPROVED** [review]
Thanks for fixing these files!

**Comment by DJDavies2** [comment]
I am getting ioda ctest failures:

test_ioda_obsspace_out_odc_compare_gmi:

000 2023-07-10 23:24:44 (E) Exception: Assertion failed: column1.type() == column2.type() in compare, line 254 of /home/d03/frwd/cylc-run/ufo-2916/share/mo-bundle/odc/src/odc/Comparator.cc

Has someone run the ODB ioda tests?

**Comment by srherbener** [comment]
> I am getting ioda ctest failures:
> 
> test_ioda_obsspace_out_odc_compare_gmi:
> 
> 000 2023-07-10 23:24:44 (E) Exception: Assertion failed: column1.type() == column2.type() in compare, line 254 of /home/d03/frwd/cylc-run/ufo-2916/share/mo-bundle/odc/src/odc/Comparator.cc
> 
> Has someone run the ODB ioda tests?

@DJDavies2 thanks for testing and reporting this. I'll look into it and let you know what I find.

**Review by PatNichols — APPROVED** [review]
Looks good. Thanks

**Comment by srherbener** [comment]
> > I am getting ioda ctest failures:
> > test_ioda_obsspace_out_odc_compare_gmi:
> > 000 2023-07-10 23:24:44 (E) Exception: Assertion failed: column1.type() == column2.type() in compare, line 254 of /home/d03/frwd/cylc-run/ufo-2916/share/mo-bundle/odc/src/odc/Comparator.cc
> > Has someone run the ODB ioda tests?
> 
> @DJDavies2 thanks for testing and reporting this. I'll look into it and let you know what I find.

@DJDavies2 I was able to reproduce the error you reported. It turns out that that the ioda-data test reference files `diagout-gmi_0000.odc` and 'diagout-amsua_0000.odc` were impacted by the changes in the companion PRs to this PR. I verified that the only differences in these two reference files is that the column `scanpos` changed from float to int. All of the values remain the same in both reference files. So I went ahead and updated these two reference files.

Please try your testing again and verify that this fixes it on your side too. Thanks!

**Comment by DJDavies2** [comment]
Thanks, the tests work for me now.

**Comment by srherbener** [comment]
> Thanks, the tests work for me now.

@DJDavies2 great news, and thanks for testing

**Comment by srherbener** [comment]
I have resolved the conflict with the `diagout-amsua_0000.odc` test reference file. I built and ran tests using the `bugfix/sensorScanPosition_integer` branches with the develop version of the `diagout-amsua_0000.odc` test reference file. I then verified that the only differences between test output (bugfix branch version) and test reference (develop version) was that scan position changed from a float to an int (where all of the values matched). In other words the only difference in the entire file is that the data type changed from float to in for scan position while the values for scan position did not change.

**Pull request merged**
