### PR TITLE
Updated reference file.

### PR DESCRIPTION
**Pull request by DJDavies2**
Updated reference file for https://github.com/JCSDA-internal/ioda/pull/663 (https://github.com/JCSDA-internal/ioda/pull/661).

### CODE REVIEW

**Comment by mo-hlawrence** [comment]
Sorry I'm struggling to checkout the branch so that I can look at the new file. I've done: git checkout feature/ioda661 under jopa-bundle/ioda-data. Do you know why this isn't working by any chance?

**Comment by DJDavies2** [comment]
I don't know why that wouldn't work, git is being a bit flaky at the moment.  How many times have you tried?  It could be a transient problem.

**Comment by mo-hlawrence** [comment]
Yes I've just had similar problems elsewhere so I guess there's something going on... I will look into it and/or keep trying.

**Review by mo-hlawrence — APPROVED** [review]
Managed to checkout the file now (had to do git pull beforehand for it to work). Looks fine to me!

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
