### PR TITLE
Files now have strings.

### PR DESCRIPTION
**Pull request by DJDavies2**
Updated files for https://github.com/JCSDA-internal/ioda/pull/419.

### CODE REVIEW

**Comment by wsmigaj** [comment]
On my machine, `ncdump` displays "NetCDF: HDF error" when asked to display the contents of these files. HDFView is able to handle them, though.

**Comment by wsmigaj** [comment]
Interestingly, `ncdump` is able to display the contents of the files I obtained by running the `test_ioda-convert_aircraft_odc` and `test_ioda-convert_groundgps_odc` tests on my machine (using the `bugfix/StringsODC` branch of ioda).

@DJDavies2 @srherbener @rhoneyager Are your versions of `ncdump` able to display the HDF files included in this PR?

**Comment by DJDavies2** [comment]
It seems to work for me, netcdf 4.7.1.

**Review by srherbener — APPROVED** [review]
I fixed the conflicts and got develop merged in. The files look good now. I can read them with ncdump as well as hdfView, and the _FillValue attributes are being set for int and float variables (none for strings yet but this can be addresses in a subsequent PR).

**Pull request merged**
