### PR TITLE
Test data for new method ObsDataVector::assignToExistingVariables(const ObsVector

### PR DESCRIPTION
**Pull request by SusanSun17**
## Description

As described in https://github.com/JCSDA-internal/ufo/issues/1619 :

In `ufo::ObsFilterData::get` https://github.com/JCSDA-internal/ufo/blob/develop/src/ufo/filters/ObsFilterData.cc#L233
these lines take the ObsVector referenced by `jv->second` and write its values into an ObsDataVector `values`. However, if the ObsVector contains missing values, these are double-type, and they get copied straight into `values`, when in fact they should be converted to float-type missing values, as appropriate for an ObsDataVector.

An example consequence: when using the BlackList filter to set diagnostic flags for a variable for which all `@HofX` values `is_not_defined:`, diagnostic flags are not set - the missing values in the H(x) ObsVector are double-type, and since they are not converted to float-type missing values correctly in `ufo::ObsFilterData::get`, the filter fails to register that they are missing when setting the diagnostic flags (but still sets `qcflags` correctly).

Proposed solution: add a new method `ioda::ObsDataVector::assignToExistingVariables`, which takes an ObsVector as argument, loops through all the ObsDataVector variables, and if they are found in the ObsVector, copies across the values from the ObsVector into the ObsDataVector, taking care to convert any missing values from double- to float-type. This new method is then called in `ufo::ObsFilterData::get`.

Some tests are added to the existing ioda ObsDataVector ctest in order to check the new method works.

### Issue(s) addressed

- fixes https://github.com/JCSDA-internal/ufo/issues/1619

## Acceptance Criteria (Definition of Done)

The ctest `test_ioda_obsdatavector` now includes 3 further tests specifically to check the `assignToExistingVariables` functionality:
- "multiple variables disordered": the ObsVector and the reference ObsDataVector contain the same variables, but in different order (respectively `[air_temperature, float_variable_3, float_variable_2]` from the ObsSpace simulated variables, and `[float_variable_2, float_variable_3, air_temperature]` listed in the YAML) - the values in the ObsVector should be copied into a blank ObsDataVector in the correct order, such as it matches the reference ObsDataVector.
- "excess variables in ObsVector": now the reference ObsDataVector only contains one variable `float_variable_2`, while the ObsVector additionally contains `float_variable_3` and `air_temperature` - these should be ignored, only copying the values of `float_variable_2` into the blank ObsDataVector.
- "variables not found in ObsVector": the reference ObsDataVector contains `float_variable_1`, which is not in the ObsVector - this should result in an exception being thrown, "not found in ObsVector".

These tests pass with `assignToExistingVariables` as written, and fail if the following deliberate errors are introduced:
- `assignToExistingVariables` does nothing: the blank ObsDataVector is unchanged by a call to `assignToExistingVariables`, and so does not match the reference ObsDataVector,
- `assignToExistingVariables` does not convert missing values correctly: calling the method on the blank ObsDataVector then results in missing values being mistaken for actual values with ridiculous values, skewing the statistics printed out, so that they do not match those of the reference ObsDataVector,
-  `assignToExistingVariables` contains errors in matching up the indices of variables in ObsVector and ObsDataVector: the test then tries to match up the wrong variables with each other, and fails because their statistics don't match (the ioda-test data is designed to make this obvious).

## Dependencies

Waiting on the following PRs:
- [ ] waiting on https://github.com/JCSDA-internal/ioda/pull/518
- [ ] waiting on https://github.com/JCSDA-internal/ufo/pull/1678

## Impact

- [ ] ioda
- [ ] ufo

### CODE REVIEW

**Review by shlyaeva — COMMENTED** [review]
Is this file meant to replace `variable_assignment_testdata.nc`? Adding this file will result in two files in ioda-data with same names, but different extensions (`.nc` and `.nc4`).

**Comment by SusanSun17** [comment]
I see - yes, I meant to replace the existing `variable_assignment_testdata.nc` - I will delete the old one and push again...

**Comment by SusanSun17** [comment]
> I see - yes, I meant to replace the existing `variable_assignment_testdata.nc` - I will delete the old one and push again...

@shlyaeva - the old `variable_assignment_testdata.nc` was being used by `test_ioda_obsspace` - I can change `iodatest_obsspace.yaml` to take the new .nc4 file as input instead, but then I also need to change [`test data.nvars`](https://github.com/JCSDA-internal/ioda/blob/develop/test/testinput/iodatest_obsspace.yml#L463) from 1 to 4 - is this expected, or problematic? The new .nc4 contains another 3 variables in the `@ObsValue` group, but the ioda test only lists 1 `simulated variables`, not any of these 3 extra variables.

Alternatively, I can reinstate the old  `variable_assignment_testdata.nc` for use in `test_ioda_obsspace`, and rename the new .nc4 to something else, for use exclusively in `test_ioda_obsdatavector`?

**Comment by shlyaeva** [comment]
> @shlyaeva - the old variable_assignment_testdata.nc was being used by test_ioda_obsspace - I can change iodatest_obsspace.yaml to take the new .nc4 file as input instead, but then I also need to change test data.nvars from 1 to 4 - is this expected, or problematic? The new .nc4 contains another 3 variables in the @ObsValue group, but the ioda test only lists 1 simulated variables, not any of these 3 extra variables.
Alternatively, I can reinstate the old variable_assignment_testdata.nc for use in test_ioda_obsspace, and rename the new .nc4 to something else, for use exclusively in test_ioda_obsdatavector?

It may be best for @srherbener to comment on this (I don't know the existing files and tests well). What do you think, Steve?

**Comment by srherbener** [comment]
> > @shlyaeva - the old variable_assignment_testdata.nc was being used by test_ioda_obsspace - I can change iodatest_obsspace.yaml to take the new .nc4 file as input instead, but then I also need to change test data.nvars from 1 to 4 - is this expected, or problematic? The new .nc4 contains another 3 variables in the @ObsValue group, but the ioda test only lists 1 simulated variables, not any of these 3 extra variables.
> > Alternatively, I can reinstate the old variable_assignment_testdata.nc for use in test_ioda_obsspace, and rename the new .nc4 to something else, for use exclusively in test_ioda_obsdatavector?
> 
> It may be best for @srherbener to comment on this (I don't know the existing files and tests well). What do you think, Steve?

I think it's better to have just the one new `variable_assignment_testdata.nc4` file. The obs space nvars() function is supposed to return the number of variables in the ObsValue group so it's okay to update the expected nvars value to 4 in the test_ioda_obsspace.

**Review by shlyaeva — APPROVED** [review]

**Review by srherbener — APPROVED** [review]

**Pull request merged**
