### PR TITLE
Sample files for the python reader example.

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR adds sample ioda v2 output files (from H(x) applications) that can be used for development of diagnostics tools. The immediate need is for the development of a ioda v2 python based tutorial.

### Issue(s) addressed

None

## Acceptance Criteria (Definition of Done)

Sample ioda v2 files are made available for use.

## Dependencies

None

## Impact

None

### CODE REVIEW

**Review by mmiesch — APPROVED** [review]
Thanks @srherbener - the first two files work great but I'm having problems with the radiosondes data:
```python
Singularity> python $PYIODA/06-ReadIodaOutputFile.py $DDD/sample_hofx_output_sondes.nc4      
['/home/ubuntu/jedi/internal/fv3-bundle/ioda/src/engines/Examples/Python/06-ReadIodaOutputFile.py', '/home/ubuntu/jedi/internal/fv3-bundle/ioda-data/testinput_tier_1/sample_hofx_output_sondes.nc4']
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: ../../src/H5D.c line 296 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../src/H5VLcallback.c line 1974 in H5VL_dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: ../../src/H5VLcallback.c line 1941 in H5VL__dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: ../../src/H5VLnative_dataset.c line 125 in H5VL__native_dataset_open(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #004: ../../src/H5Dint.c line 1482 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #005: ../../src/H5Gloc.c line 462 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #006: ../../src/H5Gtraverse.c line 855 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #007: ../../src/H5Gtraverse.c line 630 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #008: ../../src/H5Gloc.c line 418 in H5G__loc_find_cb(): object 'nchans' doesn't exist
    major: Symbol table
    minor: Object not found
Traceback (most recent call last):
  File "/home/ubuntu/jedi/internal/fv3-bundle/ioda/src/engines/Examples/Python/06-ReadIodaOutputFile.py", line 41, in <module>
    chansDimVar = og.vars.open(chansDimName)
RuntimeError: 	Reason:	An exception occurred inside ioda while opening a variable.
	name:	nchans
	source_column:	0
	source_filename:	/opt/jedi/fv3-bundle/ioda/src/engines/ioda/src/ioda/Has_Variables.cpp
	source_function:	virtual ioda::Variable ioda::detail::Has_Variables_Base::open(const string&) const
	source_line:	107

Singularity> 
```

**Comment by srherbener** [comment]
The example script in ioda feature/py-tutorial branch is currently hardwired for the radiance data. It needs an update before it can work with radiosonde (due to the variable names and dimensions being different in the radiosonde case).

Since we are both working on these scripts at the same time. Perhaps it would make sense for me to start a second script to handle the radiosonde data. That way you can continue with the current script and we won't collide. Does this sound good?

**Comment by mmiesch** [comment]
Thanks @srherbener - actually, I have another suggestion.

I'm guessing it's pretty straightforward to modify the script to read in radiosonde data - it's just a question of changing the dimensions and variable names.  So, I'm not sure it's useful as a separate example in the Examples directory.  But this is ideal for the tutorial activity!  

So, here is what I suggest:
* leave this PR unchanged and merge it, with the sonde data included
* also no need to change the feature/py-tutorial branch of ioda - we can merge that as is
* Do write a separate radiosonde script but do not add it to the ioda repo.  Instead just email it to me.
* I will write the tutorial which will walk the student through writing the script to read in the radiosonde data, using the radiance script as an example.

How does that sound?

**Comment by srherbener** [comment]
@mmiesch I think your plan sounds good. The ioda feature/py-tutorial branch is also to be merged into release/2.0.0, correct?

I like the idea of having the radiance script as guidance for creating the radiosonde version.

I'll do the PR in ioda next, followed by the radiosonde script.

Thanks!

**Pull request merged**
